### ISSUE TITLE
能否增加一个设置以允许嵌入到其他网站？

### ISSUE THREAD

**Issue by chaos-lawyer** [jiangnianshun/django-mdict#7]
想搭配 /jzohrab/lute-v3 这个项目使用，目前是拒绝访问状态
![image](https://github.com/jiangnianshun/django-mdict/assets/132078093/08ca6aa4-2cc6-4f81-86e9-ad376cfc0f22)

**Comment by jiangnianshun** [comment]
你好，并没有设置过不允许嵌入其他网站，我会在有时间的时候再检查一下可能的原因。

**Comment by chaos-lawyer** [comment]
谢谢您，浏览器调试界面显示「Refused to display 'https://xxx' in a frame because it set 'X-Frame-Options' to 'sameorigin'.」

**Comment by jiangnianshun** [comment]
你好，尝试了一下，不太行。
1、Refused to display 'https://xxx/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.这个报错是django的同源设置，需要将mysite/settings.py的第56行# 'django.middleware.clickjacking.XFrameOptionsMiddleware',注释掉，如下图
![image](https://github.com/jiangnianshun/django-mdict/assets/39703846/2a3eb993-fa01-4360-ba50-d6560d843a7a)
2、嵌入页面的iframe需要设置allow-scripts，如下图
![image](https://github.com/jiangnianshun/django-mdict/assets/39703846/d4ae7989-8320-402d-974b-dfdc6e3d9419)
3、由于django-mdict词条是在iframe里，因此是iframe嵌套iframe，默认不允许运行，需要关闭浏览器的同源策略，会降低安全性，不建议。
相关内容：
[https://stackoverflow.com/questions/25098021/securityerror-blocked-a-frame-with-origin-from-accessing-a-cross-origin-frame](https://stackoverflow.com/questions/25098021/securityerror-blocked-a-frame-with-origin-from-accessing-a-cross-origin-frame)
[https://stackoverflow.com/questions/3102819/disable-same-origin-policy-in-chrome](https://stackoverflow.com/questions/3102819/disable-same-origin-policy-in-chrome)
关闭后启动能够显示，如下图
![image](https://github.com/jiangnianshun/django-mdict/assets/39703846/53e9d31e-dd03-49c9-ae81-342f424adea3)

**Comment by chaos-lawyer** [comment]
好的，谢谢_(:з」∠)_
